### PR TITLE
mark field deprecated

### PR DESCRIPTION
**Pull request by lightsing**

### CODE REVIEW

**Review by noel2004 — APPROVED** [review]
Yes. these two fields never show in blockTrace now

**Comment by lispc** [comment]
it makes sense. But i'd better make some big PR into 0818 rather than tiny prs into main

**Comment by lispc** [comment]
@noel2004 should we merge this?

**Comment by icemelon** [comment]
@lightsing @noel2004 @lispc what's the status of this pr?

**Pull request closed without merging**
